services:
  - type: web
    name: backend
    env: node
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BETTER_AUTH_URL
        value: https://${RENDER_EXTERNAL_URL}
